version: '3.9'

services:

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"

  ai-service:
    build:
      context: ./ai-service
    container_name: sustainability-ai-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis